version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - MarkEWaite
  - jmmeessen
  - gounthar
  labels:
  - skip-changelog
